[package]
version = "0.0.1"
name = "pjsip-sys"
description = "Rust binding to PJSIP"
edition = "2018"

[lib]
name = "pjsip"
path = "src/lib.rs"

[build-dependencies]
bindgen = "0.69"
os_info = "3.12.0"
reqwest = { version = "0.12", features = ["blocking"] }
zip = "2.1"
